/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    specimens: Specimen;
    discounts: Discount;
    orders: Order;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    specimens: SpecimensSelect<false> | SpecimensSelect<true>;
    discounts: DiscountsSelect<false> | DiscountsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    settings: Setting;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Admin users who can log in to manage the collection.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role?: ('admin' | 'curator') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * All uploaded images. Cloudflare R2 handles storage; images auto-resize on upload.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for accessibility and SEO. E.g. "Seolhae Juniper bonsai in Buncheong pot".
   */
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    lightbox?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "specimens".
 */
export interface Specimen {
  id: number;
  name: string;
  latinName?: string | null;
  productType: 'flower' | 'tincture';
  category: 'flower' | 'bonsai' | 'tincture' | 'moss' | 'rare';
  image: number | Media;
  shortDescription: string;
  longDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  details?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  price35g?: number | null;
  price28g?: number | null;
  price15ml?: number | null;
  badge?: ('none' | 'new' | 'rare' | 'popular') | null;
  available?: boolean | null;
  stock?: number | null;
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Create percentage or flat-amount discounts. Apply to a single item or the whole collection.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "discounts".
 */
export interface Discount {
  id: number;
  /**
   * Your reference name — not shown to visitors. E.g. "Spring sale 20%".
   */
  label: string;
  /**
   * Choose whether the discount is a % or a fixed dollar amount.
   */
  type: 'percentage' | 'flat';
  /**
   * For percentage: enter 20 for 20%. For flat: enter 50 for $50 off.
   */
  value: number;
  scope: 'all' | 'specific' | 'category';
  /**
   * Only shown when "Specific specimens" is selected above.
   */
  specimens?: (number | Specimen)[] | null;
  /**
   * Only shown when "Entire category" is selected above.
   */
  category?: ('bonsai' | 'flower' | 'moss' | 'rare') | null;
  /**
   * Optional short text shown on the card, e.g. "20% off" or "Spring Sale". Leave blank to show no badge.
   */
  badgeText?: string | null;
  /**
   * Toggle this off to pause the discount without deleting it.
   */
  active?: boolean | null;
  /**
   * Leave blank to start immediately. The discount will not apply before this date.
   */
  startsAt?: string | null;
  /**
   * Leave blank for no expiry. The discount automatically deactivates after this date.
   */
  expiresAt?: string | null;
  showOriginalPrice?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * All submitted orders. Edit after submission — collector and team notified automatically.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  receiptId: string;
  status: 'pending' | 'confirmed' | 'fulfilled' | 'cancelled';
  collectorName: string;
  collectorEmail?: string | null;
  collectorPhone?: string | null;
  collectorMessage?: string | null;
  items?:
    | {
        name: string;
        size?: string | null;
        price: number;
        qty: number;
        subtotal?: number | null;
        id?: string | null;
      }[]
    | null;
  subtotal?: number | null;
  deliveryFee?: number | null;
  discount?: number | null;
  /**
   * Positive adds, negative subtracts.
   */
  adjustment?: number | null;
  adjustmentNote?: string | null;
  total?: number | null;
  /**
   * Team only — never sent to collector.
   */
  internalNotes?: string | null;
  fulfilledBy?: string | null;
  fulfilledAt?: string | null;
  deliveryMethod?: ('pickup' | 'delivery' | 'other') | null;
  currency?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'specimens';
        value: number | Specimen;
      } | null)
    | ({
        relationTo: 'discounts';
        value: number | Discount;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        lightbox?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "specimens_select".
 */
export interface SpecimensSelect<T extends boolean = true> {
  name?: T;
  latinName?: T;
  productType?: T;
  category?: T;
  image?: T;
  shortDescription?: T;
  longDescription?: T;
  details?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  price35g?: T;
  price28g?: T;
  price15ml?: T;
  badge?: T;
  available?: T;
  stock?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "discounts_select".
 */
export interface DiscountsSelect<T extends boolean = true> {
  label?: T;
  type?: T;
  value?: T;
  scope?: T;
  specimens?: T;
  category?: T;
  badgeText?: T;
  active?: T;
  startsAt?: T;
  expiresAt?: T;
  showOriginalPrice?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  receiptId?: T;
  status?: T;
  collectorName?: T;
  collectorEmail?: T;
  collectorPhone?: T;
  collectorMessage?: T;
  items?:
    | T
    | {
        name?: T;
        size?: T;
        price?: T;
        qty?: T;
        subtotal?: T;
        id?: T;
      };
  subtotal?: T;
  deliveryFee?: T;
  discount?: T;
  adjustment?: T;
  adjustmentNote?: T;
  total?: T;
  internalNotes?: T;
  fulfilledBy?: T;
  fulfilledAt?: T;
  deliveryMethod?: T;
  currency?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  /**
   * Used in emails and receipts.
   */
  storeName?: string | null;
  /**
   * Shown next to the logo in the header.
   */
  tagline?: string | null;
  currency?: ('USD' | 'EUR' | 'GBP' | 'KRW' | 'AUD') | null;
  /**
   * Toggle this on to show a banner at the top of the gallery.
   */
  announcementEnabled?: boolean | null;
  /**
   * E.g. "New drops every Friday" or "Closed this weekend — back Monday."
   */
  announcementText?: string | null;
  announcementType?: ('info' | 'success' | 'warning') | null;
  /**
   * Banner disappears automatically after this date. Leave blank to keep it until you uncheck above.
   */
  announcementExpiry?: string | null;
  /**
   * Large text, first line.
   */
  heroTitle?: string | null;
  /**
   * Large text, second line — shown in bronze italic.
   */
  heroTitleItalic?: string | null;
  /**
   * Shown to the right of the title.
   */
  heroSubtitle?: string | null;
  /**
   * Shown next to "3.5g" on product cards and receipts.
   */
  label35g?: string | null;
  /**
   * Shown next to "28g" on product cards and receipts.
   */
  label28g?: string | null;
  /**
   * Shown next to "15mL" on tincture cards and receipts.
   */
  label15ml?: string | null;
  deliveryFeeEnabled?: boolean | null;
  /**
   * Shown on receipt — e.g. "Delivery", "Service fee", "Handling".
   */
  deliveryFeeLabel?: string | null;
  deliveryFeeAmount?: number | null;
  /**
   * Orders at or above this amount get free delivery. Set to 0 to always charge.
   */
  deliveryFeeThreshold?: number | null;
  /**
   * Applies to all orders automatically.
   */
  discountEnabled?: boolean | null;
  /**
   * Shown on the receipt line item.
   */
  discountLabel?: string | null;
  discountType?: ('percentage' | 'fixed') | null;
  /**
   * For percentage: enter 10 for 10% off. For fixed: enter 20 for $20 off.
   */
  discountValue?: number | null;
  /**
   * Set to 0 for no minimum.
   */
  discountMinimumOrder?: number | null;
  /**
   * Shown at the bottom of the receipt.
   */
  organisersName?: string | null;
  organisersEmail?: string | null;
  receiptMessage?: string | null;
  /**
   * Optional disclaimer or terms shown at the very bottom of the receipt.
   */
  receiptFooter?: string | null;
  sendReceiptEmails?: boolean | null;
  /**
   * Leave blank to use team email set in environment variables.
   */
  notifyOrganiserEmail?: string | null;
  surpriseMeEnabled?: boolean | null;
  /**
   * Heading on the discovery banner.
   */
  surpriseMeTitle?: string | null;
  surpriseMeSubtitle?: string | null;
  surpriseMeButtonText?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  storeName?: T;
  tagline?: T;
  currency?: T;
  announcementEnabled?: T;
  announcementText?: T;
  announcementType?: T;
  announcementExpiry?: T;
  heroTitle?: T;
  heroTitleItalic?: T;
  heroSubtitle?: T;
  label35g?: T;
  label28g?: T;
  label15ml?: T;
  deliveryFeeEnabled?: T;
  deliveryFeeLabel?: T;
  deliveryFeeAmount?: T;
  deliveryFeeThreshold?: T;
  discountEnabled?: T;
  discountLabel?: T;
  discountType?: T;
  discountValue?: T;
  discountMinimumOrder?: T;
  organisersName?: T;
  organisersEmail?: T;
  receiptMessage?: T;
  receiptFooter?: T;
  sendReceiptEmails?: T;
  notifyOrganiserEmail?: T;
  surpriseMeEnabled?: T;
  surpriseMeTitle?: T;
  surpriseMeSubtitle?: T;
  surpriseMeButtonText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}